; ============================================================
;  Smart Fish Pond IoT — Firmware Node Sensor (ESP32)
;  Docs: https://docs.platformio.org/page/projectconf.html
; ============================================================

[platformio]
default_envs = esp32dev

[env]
platform = espressif32@^6.5.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Wall

[env:esp32dev]
board = esp32dev

[env:esp32dev-ota]
board = esp32dev
upload_protocol = espota
upload_port = 192.168.1.50   ; ganti dengan IP device saat OTA
